
{% set name = "xmlf90" %}
{% set version = "1.5.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/garalb/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5b2e3d4e6ea5fa5afa1edefcb1f11bc0ed03f0ca3c28aa2fc148adb466362c8e

build:
  number: 0
  skip: true  # [win]
  
requirements:
  build:
    - {{ compiler('fortran') }}
    - cmake
    - ninja

about:
  home: https://gitlab.com/siesta-project/libraries/xmlf90
  summary: 'A lightweight XML parser and generator in Fortran'
  description: |
  
        xmlf90 is a suite of libraries to handle XML in Fortran. A
	first component is a XML parsing library, designed to be a
	useful tool in the extraction and analysis of data in the
	context of scientific computing. The priorities were
	efficiency and the ability to deal with very large XML files
	while maintaining a small memory footprint. The most complete
	programming interface is based on the very successful SAX
	(Simple API for XML) model, although a partial DOM interface
	and a very experimental XPATH interface are also present. Also
	included is a library (xmlf90-wxml) that facilitates the
	writing of well-formed XML, including such features as
	automatic start-tag completion, attribute pretty-printing, and
	element indentation. There are also helper routines to handle
	the output of numerical arrays.

  # Remember to specify the license variants for BSD, Apache, GPL, and LGPL.
  # Use the SPDX identifier, e.g: GPL-2.0-only instead of GNU General Public License version 2.0
  # See https://spdx.org/licenses/
  license: BSD-2-Clause
  # The license_family, i.e. "BSD" if license is "BSD-3-Clause". 
  # Optional
  license_family: BSD
  # It is required to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # Please also note that some projects have multiple license files which all need to be added using a valid yaml list.
  # See https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#license-file
  license_file: COPYING
  # The doc_url and dev_url are optional.
  ## doc_url: https://simplejson.readthedocs.io/
  ## dev_url: https://github.com/simplejson/simplejson

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - albgar
